spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:2020/validateToekn
